### ISSUE TITLE
Improve "known teams" websocket message

### ISSUE THREAD

**Issue by greedykangaroo01** [robocup-logistics/rcll-refbox#164]
Currently, the known teams are distributed to the frontend via a message array always containing a single message with an array of the known teams. Instead of an array of messages, only a single websocket message should be sent

**Comment by snoato** [comment]
The problem here is that this is implemented on the backend using a generic function (`on_connect_info`). This function is designed to work in cases where there is one OR multiple concurrent facts. Since this is probably only a small quality of life improvement on the frontend, but would require reworking generic code for a specific case I'm not sure if we should actually go forward with this.
