### ISSUE TITLE
Not enough points awarded for higher complexity products

### ISSUE THREAD

**Issue by TarikViehmann** [robocup-logistics/rcll-refbox#37]
When producing a C3 that requires two rings with color complexity 0 and one ring with higher complexity, the 5 points for color complexity 0 are only added once instead of twice. Not sure if this issue becomes obsolete in #30, as i did not have time to review it, yet.

```
13:33:49.048008 C: Giving 10 points to team CYAN: Mounted cap for order 2 (PRODUCTION @ 259.279909)
13:33:49.048255 C: Giving 80 points to team CYAN: Mounted last ring for complexity C3 order 2 (PRODUCTION @ 259.279909)
13:33:49.048496 C: Giving 10 points to team CYAN: Mounted CC1 ring of CC1 for order 2 (PRODUCTION @ 259.279909)
13:33:49.048741 C: Giving 5 points to team CYAN: Mounted CC0 ring of CC0 for order 2 (PRODUCTION @ 259.279909)
13:33:49.049013 C: Giving 20 points to team CYAN: Delivered item for order 2 (PRODUCTION @ 259.279909)
13:33:49.049278 C: Machine C-DS finished processing
```

**Comment by MostafaGomaa** [comment]
I checked the code and this was indeed a bug, good catch!
The reason is that there was 2 "point" facts asserts with the exact same parameters for both of the CC0 rings. Ofcourse, only one of which will end up making it to the fact base.

This is fixed by PR #30 as the points now are related to the unique operation ID they were awarded for.
A motive to look into the PR, maybe ;)
