### ISSUE TITLE
Points for C3 incorrect

### ISSUE THREAD

**Issue by thomerz** [robocup-logistics/rcll-refbox#8]
The way points are calculated for C3 differ from the way it is done for C1 and C2 products. For both C1 and C2, points are assigned for mounting 1 and 2 rings, respectively, as well as for mounting the last ring. For C3, points for mounting rings 1 and 2 but not 3 are assigned, followed by assigning points for mounting the last ring. 

I attached a logfile copied from the refbox shell for clarification.

----------------------------------------------------------------------

│16:09:59.018 A: Order 4: 1 x C3 from 11:37 to 14:20
│16:09:59.021 A: Order 2: 1 x C1 from 00:00 to 17:00
│16:09:59.022 A: Order 1: 1 x C0 from 00:00 to 17:00
│16:10:22.027 A: Order 3: 1 x C2 from 11:09 to 14:01

- Here we can see, points are awarded for mounting a ring of complexity CC2
- as well as for mounting the last ring of order 2, which is a C1

│16:11:48.704 L: Sending completed order for team MAGENTA (base: BASE_RED, rings: RING_GREEN, cap: CAP_GREY)
│16:11:48.740 C: Awarding 20 points to team MAGENTA: Delivered item for order 2 (PRODUCTION @ 109.723537)
│16:11:48.741 C: Awarding 10 points to team MAGENTA: Mounted cap for order 2 (PRODUCTION @ 109.723537)
│16:11:48.741 C: Awarding 10 points to team MAGENTA: Mounted last ring for complexity C1 order 2 (PRODUCTION @ 109.723537)                                                                                    
│16:11:48.741 C: Awarding 20 points to team MAGENTA: Mounted CC2 ring of CC2 for order 2 (PRODUCTION @ 109.723537)

- Here, for the C2 product from order 3, points are awarded for mounting
- rings 1 (CC0) and 2 (CC2), respectively. Also, points for mounting the
- last ring are awarded.

│16:21:41.869 L: Sending completed order for team MAGENTA (base: BASE_RED, rings: RING_YELLOW|RING_GREEN, cap: CAP_GREY)
│16:21:41.897 C: Awarding 20 points to team MAGENTA: Delivered item for order 3 (PRODUCTION @ 702.880562999996)
│16:21:41.898 C: Awarding 10 points to team MAGENTA: Mounted cap for order 3 (PRODUCTION @ 702.880562999996)
│16:21:41.898 C: Awarding 30 points to team MAGENTA: Mounted last ring for complexity C2 order 3 (PRODUCTION @ 702.880562999996)
│16:21:41.898 C: Awarding 20 points to team MAGENTA: Mounted CC2 ring of CC2 for order 3 (PRODUCTION @ 702.880562999996)
│16:21:41.899 C: Awarding 5 points to team MAGENTA: Mounted CC0 ring of CC0 for order 3 (PRODUCTION @ 702.880562999996)

- For the C3 product from order 4, points are only awarded for mounting
- rings 1 and 2, followed by awarding points for mounting the last ring.

│16:22:35.045 L: Sending completed order for team MAGENTA (base: BASE_RED, rings: RING_BLUE|RING_YELLOW|RING_GREEN, cap: CAP_GREY)
│16:22:35.057 C: Awarding 20 points to team MAGENTA: Delivered item for order 4 (PRODUCTION @ 756.040481999995)
│16:22:35.057 C: Awarding 10 points to team MAGENTA: Mounted cap for order 4 (PRODUCTION @ 756.040481999995)
│16:22:35.057 C: Awarding 80 points to team MAGENTA: Mounted last ring for complexity C3 order 4 (PRODUCTION @ 756.040481999995)
│16:22:35.057 C: Awarding 20 points to team MAGENTA: Mounted CC2 ring of CC2 for order 4 (PRODUCTION @ 756.040481999995)
│16:22:35.057 C: Awarding 5 points to team MAGENTA: Mounted CC0 ring of CC0 for order 4 (PRODUCTION @ 756.040481999995)

**Comment by morxa** [comment]
Hm, this one is interesting. This may actually be correct, because points are only given if such an order actually exists. If you mount the first ring and a C1 order exists with that ring color, then you get points, otherwise you don't.

From the rules:
> Points are only awarded if there is yet an order for which the performed step is required and which has not yet expired (the end of the order time window has not yet passed) and for which the step has not been performed for as often as products have been requested. For example, consider a C 1 order with a single ring of which two products have been requested. When the appropriate ring of that C 1 product is mounted, the appropriate points (for finishing a C 1 pre-cap) are awarded if and only if the end time of the delivery window of that order has not passed and the step has not been completed more than two times (including the just performed step). Therefore, only production steps which can be determined to belong to an upcoming (and announced) or on-going order can be awarded. Performing a step for a later order which has not yet been announced cannot be awarded.

So it really depends on which orders were active. Do you still have the full log including the order info?

I would actually say that this part of the rules is odd, because you get different points for a C3 delivery depending on which other orders exist. We may want to change that, but it's not a bug in the refbox (if that's what happened here).

**Comment by thomerz** [comment]
No unfortunatelly I did only safe the log I provided above. I can try to replicate the results. However, I must admit I do not get (from the rules), why you would not get the points for mounting one of the 3 rings. At least the C3 order was active since delivery points where awarded.

Anyhow, as you pointed out, I think it is odd to award fewer points for a C3, based on other existing orders.

**Comment by morxa** [comment]
The rules are still ambiguous, and I would actually understand them differently:
1. Points are only awarded if a matching order exists
1. Points are only awarded for the *last* ring of a product

This means if there is only a C3 order, we should only get points for the last ring, because there is no matching order for the other rings where that ring is the last mounted ring. This is probably unintended, but that's how I understand the rules.

**Comment by timn** [comment]
I think this is a misunderstanding. You do, indeed, score only for the last ring and only if the product matches an order. However, you then also score for the color complexities (which concerns every ring, since for a C3 you also need to do more work if the first ring is CC2, rather than CC0). And this is where our fact base becomes ambiguous.

To put it differently, in the scoring table, what you describe in 2. are the "pre-cap" points. What I describe are the "Finish CC_n step" points. Either have the requirement, that a valid product is delivered.
